version: '3.6'
services:
  ctfd:
    build: docker/ctfd
    user: root
    restart: always
    ports:
      - 8000:8000
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=postgres://postgres:ctfd@postgres:5432/postgres
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
    depends_on:
      - postgres
      - cache
    networks:
      default:
      internal:
  nginx:
    image: nginx:1.17
    restart: always
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ctfd
  cache:
    image: redis:4
    restart: always
    volumes:
      - redis_data:/data
    networks:
      internal:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ctfd
    ports:
      - 127.0.0.1:11432:5432
    networks:
      internal:
      access:
  graphql:
    image: hasura/graphql-engine:v2.0.0-beta.2.cli-migrations-v3
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - postgres
      # let ctfd populate the db before we run any migrations
      - ctfd
    restart: always
    volumes:
      - ./hasura:/hasura
    environment:
      HASURA_GRAPHQL_METADATA_DIR: /hasura/metadata
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura/migrations
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:ctfd@postgres:5432/postgres
      # use the cli
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      #HASURA_GRAPHQL_WS_READ_COOKIE: 'true'
      #HASURA_GRAPHQL_DISABLE_CORS: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log,
        query-log
    networks:
      default:
      internal:
      access:
volumes:
  db_data:
  redis_data:
networks:
  default:
  internal:
    internal: true
  access:
