schema:
  - schema.graphql
overwrite: true
config:
  scalars:
    DateTime: Date
    JSON: "{ [key: string]: any }"
documents:
  - ./src/**/*.tsx
  - ./src/**/*.ts
  - '!./src/generated/**/*'
generates:
  ./src/generated/hasura/ts.ts:
    plugins:
      - graphql-codegen-hasura-typescript
    config:
      reactApolloVersion: 3
      typescriptCodegenOutputPath: "../"
      trimString:
      withClientAndCacheHelpers: true
      withQueries: true
      withSubscriptions: true
      withInserts: true
      withUpdates: true
      withDeletes: true
  ./src/generated/hasura/react.ts:
    plugins:
      - graphql-codegen-hasura-react
    config:
      reactApolloVersion: 3
      typescriptCodegenOutputPath: "../"
      trimString:
      withQueries: true
      withSubscriptions: true
      withInserts: true
      withUpdates: true
      withDeletes: true
  ./src/generated/hasura/config.ts:
    plugins:
      - graphql-codegen-hasura-client-config
    config:
      reactApolloVersion: 3
      typescriptCodegenOutputPath: "../"
      trimString:
      withTypePolicies: true
      withResolverTypes: true
      withCombinedTypePolicyObject: false
      withCacheRedirects: true
      withCombinedCacheRedirectObject: true
  ./src/generated/graphql.schema.json:
    plugins:
      - introspection
  ./src/generated/index.tsx:
    documents:
      - ./src/**/*.tsx
      - ./src/**/*.ts
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      reactApolloVersion: 3
      withHooks: true
      withHOC: false
      withComponent: false
      skipTypename: false
      includeDirectives: true
