schema:
  - http://localhost:8080/v1/graphql:
      headers:
        user-agent: codegen
config:
  scalars:
    DateTime: Date
    JSON: "{ [key: string]: any }"
generates:
  ./src/generated/hasura/ts.ts:
    documents:
      - ./src/customFragments.ts
    plugins:
      - graphql-codegen-hasura-typescript
    config:
      reactApolloVersion: 3
      typescriptCodegenOutputPath: "../"
      trimString:
      withClientAndCacheHelpers: true
      withQueries: true
      withSubscriptions: true
      withInserts: true
      withUpdates: true
      withDeletes: true
  ./src/generated/hasura/react.ts:
    documents:
      - ./src/customFragments.ts
    plugins:
      - graphql-codegen-hasura-react
    config:
      reactApolloVersion: 3
      typescriptCodegenOutputPath: "../"
      trimString:
      withQueries: true
      withSubscriptions: true
      withInserts: true
      withUpdates: true
      withDeletes: true
  ./src/generated/hasura/config.ts:
    documents:
      - ./src/customFragments.ts
    plugins:
      - graphql-codegen-hasura-client-config
    config:
      reactApolloVersion: 3
      typescriptCodegenOutputPath: "../"
      trimString:
      withTypePolicies: true
      withResolverTypes: true
      withCombinedTypePolicyObject: false
      withCacheRedirects: true
      withCombinedCacheRedirectObject: true
  ./src/generated/hasura/gql.ts:
    plugins:
      - graphql-codegen-hasura-gql
    documents:
      - ./src/customFragments.ts
    config:
      reactApolloVersion: 3
      typescriptCodegenOutputPath: ../
      trimString:
      withQueries: true
      withSubscriptions: true
      withInserts: true
      withUpdates: true
      withDeletes: true
  ./src/generated/graphql.schema.json:
    plugins:
      - introspection
  schema.graphql:
    plugins:
      - schema-ast
  ./src/generated/index.tsx:
    documents:
      - ./src/**/*.tsx
      - ./src/**/*.ts
      - ./src/generated/hasura/gql.ts
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      reactApolloVersion: 3
      withHooks: true
      withHOC: false
      withComponent: false
      skipTypename: false
      includeDirectives: true