version: 3
# run hasura-cli in the same container as the dev hasura instance
# there is an alias for this in .envrc
endpoint: http://localhost:8080
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
