version: 3
# run hasura-cli with docker-compose exec graphql hasura-cli ...
endpoint: http://localhost:8080
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
