table:
  name: config
  schema: public
select_permissions:
- permission:
    columns:
    - id
    - key
    - value
    filter:
      key:
        _iregex: (ctf|user_mode|start|end|visibility|freeze)
  role: ctfd_user
